### ISSUE TITLE
Games appear twice

### ISSUE THREAD

**Issue by jfmongrain** [nyash-qq/galaxy-plugin-twitch#13]
Games appear twice in the library, once under Amazon and once under Twitch, but only the Twitch category appears in the left bar.  This happened since I upgraded to the latest version.

I did uninstall Galaxy, deleted the folder and installed it anew, none to avail.

**Comment by Rall3n** [comment]
Might be same as #12. Have you just deleted the old version without disconnecting it through Galaxy?
If so I recommend you follow the steps described [here](https://github.com/nyash-qq/galaxy-plugin-twitch/issues/12#issuecomment-531508858).

**Comment by jfmongrain** [comment]
Worked like a charm, thank you!

De : Rall3n <notifications@github.com>
Envoyé : 17 septembre 2019 02:25
À : nyash-qq/galaxy-plugin-twitch <galaxy-plugin-twitch@noreply.github.com>
Cc : jfmongrain <jfmongrain@protonmail.com>; Author <author@noreply.github.com>
Objet : Re: [nyash-qq/galaxy-plugin-twitch] Games appear twice (#13)

Might be same as [#12](https://github.com/nyash-qq/galaxy-plugin-twitch/issues/12). Have you just deleted the old version without disconnecting it through Galaxy?
If so I recommend you follow the steps described [here](https://github.com/nyash-qq/galaxy-plugin-twitch/issues/12#issuecomment-531508858).

**Comment by Rall3n** [comment]
Then I might suggest either you @jfmongrain or @nyash-qq close this issue as it seems to be resolved.
