### ISSUE TITLE
When I try to intagrate your twich addon it tells me "Plugin has crashed. Retry

### ISSUE THREAD

**Issue by AlbertovoladorMC** [nyash-qq/galaxy-plugin-twitch#14]
https://github.com/nyash-qq/galaxy-plugin-twitch/releases/tag/0.1 unzipped it and dropped it into the pluggins folder.

**Comment by nyash-qq** [comment]
Use new version https://github.com/nyash-qq/galaxy-plugin-twitch/releases/tag/0.4
