### ISSUE TITLE
inv install not working

### ISSUE THREAD

**Issue by erstaunlicherweise** [nyash-qq/galaxy-plugin-twitch#15]
The "inv install" command will not work for me,
my output ist
>C:\WINDOWS\system32\galaxy-plugin-twitch> inv install
inv : Can't find any collection named 'tasks'!

Did I miss something?

**Comment by nyash-qq** [comment]
First of all, you shall never put(and run) anything under `Windows` folder. Never. This is malicious. If you don't care about the folder used, use `%TEMP%`.
Make sure content of the cloned plugin is full, and you are running `inv` command from appropriate folder. In this case, `inv` cannot find `tasks.py` file.
