### ISSUE TITLE
Plugin apparently causes Origin plugin to crash

### ISSUE THREAD

**Issue by MattHorn25** [nyash-qq/galaxy-plugin-twitch#16]
Hello,

I have version 0.4 of this plugin installed on Galaxy 2.0.7.22 - after initially installing the plugin as per the standard procedure, on next Galaxy startup the Origin plugin reported that it crashed/couldn't start (in the plugin list in Settings). I clicked the Retry option a few times, Origin tried starting but crashed again each time.

Now, after that happened I exited Galaxy, moved the Twitch folder (twitch_8b831aed-dd5f-c0c5-c843-41f9751f67a2) elsewhere, then restarted Galaxy - and Origin loaded normally with no issues. I then exited Galaxy again, moved the Twitch folder _back_ into 'installed' and restarted Galaxy _again_ and Origin and all other plugins then loaded normally. All plugins are now working, but having seen a similar issue mentioned on Reddit by others:

https://www.reddit.com/r/gog/comments/daspxm/galaxy_20_origin_plugin/

I thought it's worth reporting. Thanks.

**Comment by into-the-intraverse** [comment]
Thanks for your report, but plugin code does not interfere with other plugins code anyhow. 
If plugins indeed do interfere with each other, then this is clearly a problem at GLX side and should be reported to the GOG.
