### ISSUE TITLE
Not in integrations list

### ISSUE THREAD

**Issue by redshojin** [nyash-qq/galaxy-plugin-twitch#18]
Downloaded the latest version and put it in the plugin folder, restarted GLX, but it's not available to connect to.

**Comment by into-the-intraverse** [comment]
Make sure you've unpacked all plugin files and folders (twitch_db_client.py, twitch_launcher_client.py, twitch_plugin.py, aiohttp\, async_timeout\ e.t.c.) directly into appropriate folder: _c:\Users\<username>\AppData\Local\GOG.com\Galaxy\plugins\installed\twitch_8b831aed-dd5f-c0c5-c843-41f9751f67a2_.
If this still doesn't work for you, please contact GOG support.
