### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by jhnkly** [nyash-qq/galaxy-plugin-twitch#2]
After running "inv install" in galaxy-plugin-twitch I get the following:
> ...
>   File "C:\Users\xxxx\galaxy-plugin-twitch\tasks.py", line 8, in <module>
>     from galaxy.tools import zip_folder_to_file
> ModuleNotFoundError: No module named 'galaxy'

**Comment by Danyelalejandro** [comment]
I had the same error tryiing to install from source code.
Nevertheless, an easy solution is to download the latest release from https://github.com/nyash-qq/galaxy-plugin-twitch/releases and unzip the folder and attach it to:
(WINDOWS) %localappdata%\GOG.com\Galaxy\plugins\installed
(MACOS) ~/Library/Application Support/GOG.com/Galaxy/plugins/installed

**Comment by jhnkly** [comment]
Ah, I wish that was included in the ReadMe!
