### ISSUE TITLE
Does this still work? 

### ISSUE THREAD

**Issue by kernaldave** [nyash-qq/galaxy-plugin-twitch#30]
It seems like no matter what I do I can not get this to work.  I put all the contents of the master folder as is in the root twitch plugin folder(TPF) and I get nothing, I take take the scr folder files or the test folder files and put them in the root (TPF), cant do both because they both have __init__.py files, and the integration shows up, but fails immediately to connect, I have tried every combination of these files from the master folder and it fails every time.  Any help would be appreciated

**Comment by Rall3n** [comment]
Have you used the git repo directly or the release archive?

Could you provide the folders you used and where you moved them (paths would be helpful here)?

**Comment by kernaldave** [comment]
I downloaded it from here on git hub (clone or download)  I created the twitch folder
C:\Users\kerna\AppData\Local\GOG.com\Galaxy\plugins\installed\twitch_8b831aed-dd5f-c0c5-c843-41f9751f67a2  

I then used 7zip and winzip to extract it.  I have tried putting the galaxy-plugin-twitch-master folder, in the twitch 8b831.... folder, and get nothing, I have taken every thing inside the galaxy-plugin-twitch-master copy/pasted and also tried extracting to twitch 8b831....., and get nothing. 

 I have I have taken the files from the src folder (__init__.py, manifest.json twitch_db_client.py, twitch_launcher_client.py, twitch_plugin.py_) and put it in the root twitch 8b813..... folder with and without the files in the root galaxy-plugin-twitch-master folder (.gitnor, LICENSE, pytest.ini, README.md, requirements.txt, requirements-release.txt, tasks.py)  when I do this the extension shows up in galaxy but fails to connect.  I have tried adding the test folder into the mix and that doesn't fix it either and have to choose one of the __init__.py files.  

Thank you for the fast response,

**Comment by Rall3n** [comment]
@kernaldave Using the option to `clone or download` is the wrong choice. That provides you with the source code, which is in general missing some required libraries. **You have to download and install the plugin from the [releases page ](https://github.com/nyash-qq/galaxy-plugin-twitch/releases)!**

**Comment by kernaldave** [comment]
Yep, now I feel like and idiot, That worked!!  Thank you, I will close this.
