### ISSUE TITLE
The free game of July "Turok 2" shows up in GOG Galaxy as "Unkown Game"

### ISSUE THREAD

**Issue by DiaBomb** [nyash-qq/galaxy-plugin-twitch#34]
I confirmed this by installing Turok 2 with the Twitch app. GOG Galaxy will then change the unknown game to playable. I then started it trough Galaxy to make sure it was Turok 2 which was true.
![Annotation 2020-07-01 215345](https://user-images.githubusercontent.com/67710562/86285935-d5f92000-bbe5-11ea-87b9-2691d8806b0b.png)

**Comment by DiaBomb** [comment]
Update: After the GOG Galaxy update 2.0.17 Turok 2 now shows up as a secondary game for Turok 1 while also being called like the Original Turok.
![Annotation 2020-07-02 110304](https://user-images.githubusercontent.com/67710562/86339246-a4b73900-bc53-11ea-9615-beefaf0598cc.png)

**Comment by Rall3n** [comment]
Plugins for GOG Galaxy 2.0 only deliver names and unique identifiers (to prevent duplicate imports). The rest (lookup for existing game info, images, etc.) is done by the client itself.

Feedback regarding this issue should be send to GOG using the "Send feedback" option in the Galaxy 2.0 client.
