### ISSUE TITLE
Can't install any games from Twitch, it says "Not compatible"

### ISSUE THREAD

**Issue by Fantus77** [nyash-qq/galaxy-plugin-twitch#4]
I can see all of the games I have associated with my twitch library. However the Install button is grayed out and when I hover over it, the pop up says "Not compatible".

Restarting Galaxy doesn't fix it. And refreshing integrations doesn't fix it.

**Comment by nyash-qq** [comment]
It's a know bug on the GLX side and it's claimed to be fixed soon.

**Comment by frozaum** [comment]
nice

**Comment by Danyelalejandro** [comment]
Hello dear @nyash-qq 

I have twitted GOG developers about the Install option:
![image](https://user-images.githubusercontent.com/53067616/66258542-f6d23900-e76b-11e9-8eb1-58c45015a848.png)
https://twitter.com/DanielLievan/status/1180142423013560321?s=20
And thay answered this:
![image](https://user-images.githubusercontent.com/53067616/66258552-0f425380-e76c-11e9-822f-c858b976ad6a.png)
https://twitter.com/LKukawski/status/1180148188067573765?s=20
I have reported this on the cogwheel of GLX and nothing seems to happen...
They have replied something to you? 
Thanks a lot!!!

**Comment by nyash-qq** [comment]
With all the respect to Lukasz, I believe he's just a community manager, so he might not be into all the technical details. 2 and [3](https://github.com/gogcom/galaxy-integrations-python-api/issues/68) are definitely by the Galaxy team's side, and AFAIK it's in progress.

**Comment by Danyelalejandro** [comment]
Oh. Ok, thank you @nyash-qq let´s hope they can fix this :)

**Comment by into-the-intraverse** [comment]
GOG released API that allows to fix this, and I fixed it in https://github.com/nyash-qq/galaxy-plugin-twitch/tree/0.5, yet we have to wait untill GLX supports this.

**Comment by into-the-intraverse** [comment]
Finally fixed in GLX
