### ISSUE TITLE
[Enhancement] Use the Twitch platform ID

### ISSUE THREAD

**Issue by Itay080** [nyash-qq/galaxy-plugin-twitch#8]
Twitch platform ID has been added to the API
https://github.com/gogcom/galaxy-integrations-python-api/commit/8d6ec500f97e74efd709902cad2447dafc1b7397

**Comment by nyash-qq** [comment]
This is just a record in the plugin API. To start using it, Twitch also has to be supported in the GLX Client. Until then, and the GLX cannot recognize it:
```
Failed to parse plugin manifest, exception: Unrecognized SupportedPlatform value: twitch
```
(and you wouldn't see it on the list of plugins)

**Comment by Itay080** [comment]
You're right, it's not yet implemented in the client. Sorry for misleading you!

**Comment by Danyelalejandro** [comment]
Dear @nyash-qq let us know when you update the plugin with this new client. Hopefully they can fix the GLX client so we can use the install option.

**Comment by nyash-qq** [comment]
Done `51d8edc5be60a96b6b991c1f200283fcbce7623a`.
