### ISSUE TITLE
Some games that had metadata before the latest release no longer have metadata

### ISSUE THREAD

**Issue by Itay080** [nyash-qq/galaxy-plugin-twitch#9]
Hi!
Thanks for the new release, it works great but some games that had metadata before the latest release no longer have metadata.
In this picture you can see an example, Observer, AER and Devil May Cry HD do not have pictures and when I click any of them I get an error message saying "Sorry, we couldn't load the data". You can see this in the second picture.
![image](https://user-images.githubusercontent.com/9900522/64873457-cbb76680-d651-11e9-9d35-a1d77d4788d3.png)

![image](https://user-images.githubusercontent.com/9900522/64873540-f6a1ba80-d651-11e9-9644-eefa6b994d8e.png)

I have more games doing it with the latest release, I can list them all if necessary.
Here is my log file
[plugin-twitch-8b831aed-dd5f-c0c5-c843-41f9751f67a2.zip](https://github.com/nyash-qq/galaxy-plugin-twitch/files/3610613/plugin-twitch-8b831aed-dd5f-c0c5-c843-41f9751f67a2.zip)

**Comment by nyash-qq** [comment]
This is by GLX side. Plugin just returns list of owned games (ids and names), while all media is managed by GLX and GOG backend services. And it look like GOG services are having hard times right now, returning lots of error on image requests.
So, there is nothing I could do here. Sooner (let's hope for that) or later, GOG will resolve this.
